### ISSUE TITLE
Password Postgres issue

### ISSUE THREAD

**Issue by burakchales** [mydexchain/mydexchain#10]
when i pull container and dockers attach mydexchain after than i take this issues 

postgres@postgres FATAL:  password authentication failed for user "postgres"
2021-01-12 17:13:24.207 +03 [2579] postgres@postgres DETAIL:  Password does not match for user "postgres".

**Comment by kadir1453** [comment]
Aynen bilarerim tamam inandım. Daha zorlamayın beni , kötü sonuçlara varmayalım12 Oca 2021 17:23 tarihinde burakchales <notifications@github.com> yazdı:
when i pull container and dockers attach mydexchain after than i take this issues
postgres@postgres FATAL:  password authentication failed for user "postgres"
2021-01-12 17:13:24.207 +03 [2579] postgres@postgres DETAIL:  Password does not match for user "postgres".

**Comment by burakchales** [comment]
> Aynen bilarerim tamam inandım. Daha zorlamayın beni , kötü sonuçlara varmayalım12 Oca 2021 17:23 tarihinde burakchales <notifications@github.com> yazdı: when i pull container and dockers attach mydexchain after than i take this issues postgres@postgres FATAL: password authentication failed for user "postgres" 2021-01-12 17:13:24.207 +03 [2579] postgres@postgres DETAIL: Password does not match for user "postgres". —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

Dostum ne diyorsun burası sohbet yeri değil ne alaka

**Comment by mydexchain-admin** [comment]
when i pull container and dockers attach mydexchain after than i take this issues

postgres@postgres FATAL: password authentication failed for user "postgres"
2021-01-12 17:13:24.207 +03 [2579] postgres@postgres DETAIL: Password does not match for user "postgres".

this is a normal behaviour, process resetting the password with random, pls ignore
