### ISSUE TITLE
specific platform was requested

### ISSUE THREAD

**Issue by ByNiKoTiN** [mydexchain/mydexchain#12]
Docker kurulumundan sonra,  MyDexChain docker file kurulumunda
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm/v7) and no specific platform was requested
Hatasını alıyorum. başka uygulamalar da docker 19.03.13 sürümü ile bu sorunu aşanlar var 
Sizin bu sorun için bir öneriniz var mı  ?

**Comment by erol7878** [comment]
Bilgisayarın güncel olduğundan emin ol..

16 Oca 2021 Cmt 01:23 tarihinde ByNiKoTiN <notifications@github.com> şunu
yazdı:

**Comment by ByNiKoTiN** [comment]
Digest: sha256:c14ecd847093837cfa2c03dd8deca573424edc691ab12d1b0665cb2f00ea5178
Status: Downloaded newer image for mydexchain/mydexchain:latest
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
c33a2573a6a4a24018b83a8a353a11a438b963648e6312d97a266935f7829950
bilgisayarım güncel.
buna benzer hataları başka uygulamalarda alanlar var onları inceledim. docker 20.x sürümünden sonra arm64 için bu hatayı aldıklarını yazmışlar ve geliştiriciler hızlı bir şekilde bunu düzeltmişler. 
umarım bizim için de bir güncelleme ile bu sorunu ortadan kaldırabilirler.

**Comment by mydexchain-admin** [comment]
merhaba, işlemcinizin tam modeli nedir acaba?

**Comment by ByNiKoTiN** [comment]
Broadcom BCM2711, Quad core Cortex-A72 (ARM v8) 64-bit SoC @ 1.5GHz

**Comment by mydexchain-admin** [comment]
Merhaba, testlerimizi tamamladık. Docker container kullandığımızdan şu an desteklemesi gerekiyor.

**Comment by ByNiKoTiN** [comment]
Öncelikle ilginiz için çok teşekkür ederim @mydexchain-admin .
Aynı hatayı almaya devam ediyorum. 

https://hizliresim.com/rNgtG3
