### ISSUE TITLE
node kurulum

### ISSUE THREAD

**Issue by adembuyuk** [mydexchain/mydexchain#13]
mydexchain node kurulum video formatında lazım.

adembuyukdumlu@gmail.com

gönderebilirsiniz

**Comment by erol7878** [comment]
https://akademi.dexchain.tv/ gereken bilgilere burada ulaşabilirsiniz.

19 Oca 2021 Sal 02:37 tarihinde adembuyuk <notifications@github.com> şunu
yazdı:

**Comment by adembuyuk** [comment]
vds de kuramadık. sanal pc üzerinde docker hata veriyor. kuran oldumu
