### ISSUE TITLE
vds de node tutma yapılırmı 

### ISSUE THREAD

**Issue by adembuyuk** [mydexchain/mydexchain#14]

**Comment by adembuyuk** [comment]
docker kurulumda problem yaşıyoruz. 
vds de docker kuran oldumu yardım edecek var mıdır

**Comment by mydexchain-admin** [comment]
sunucunu vds olması bir sorun teşkil etmez ama tavsiyemiz ubuntu üzerinde docker kurup node çalıştırmanız üzerinedir.
