### ISSUE TITLE
caught invali caracter < 

### ISSUE THREAD

**Issue by musti5400** [mydexchain/mydexchain#15]
Node bu hata ile karsilasti nasil cozulur.

**Comment by mydexchain-admin** [comment]
Hata detaylarını yazabilir misiniz?

**Comment by dexdeveloper** [comment]
Tüm bilgisayarlarda "Caught invalid character '<' looking for beginning of value" hatası alıyorum ve localhost'a bağlantı hatası oluşuyor.

**Comment by mydexchain-admin** [comment]
Problem giderildi bilgilendirme için teşekkürler.
