### ISSUE TITLE
docker 0 Bytes / 0 Bytes DISK READ/WRITE hiç hareket görmüyor. ayrıca logs alanında da hareket yok

### ISSUE THREAD

**Issue by Semra45** [mydexchain/mydexchain#17]
şuan online ve çalışıyor gözükmesine rağmen 0 Bytes / 0 Bytes
DISK READ/WRITE   ağ = 0 bytes  bu sorun nasıl düzeltilebilir.

**Comment by cryptoitems** [comment]
aynı sorun bende ve bir kaç tanıdığımda da mevcut... Ekran görüntüsü ektedir:

Docker da mydexchain konteyner da

Logs bölümü nde hiç bir şekilde ekran görüntüsü gelmiyor boş ekran gözüküyor ve

 istatistikler bölümünde 
'Cpu Usage' aktif, 
'Memory Usage' aktif, 
'Network ı/o' aktif çalışıyor  

fakat "disk read/write" bölümü başlatıldığı günden beri 0 bytes/ 0 bytes olarak gözüküyor.
 
 
![Node Hata sı mı](https://user-images.githubusercontent.com/77307182/105822615-57266300-5fcd-11eb-8298-78933c735f38.jpg)


aynı konu başlığı varken tekrar konu başlığı açmayı uygun görmediğim için konuyu takipteyim.

**Comment by mydexchain-admin** [comment]
Disk I/O sync olduğu sürece ve anlık olarak görülecektir.
docker attach mydexchain ekranında sync mesajları geldiği problem yok.
Teşekkürler.
