### ISSUE TITLE
azure da node tutma

### ISSUE THREAD

**Issue by e2503Necmettin** [mydexchain/mydexchain#19]
merhaba,
biz Amazon Web Services, Azure,  Google Cloud bunlarda birinde node tumak istiyoruz. 30-35  kişilk bir grubuz. ama teknik bilgimiz pek yok. yardımcı olabilir misiniz.

**Comment by erol7878** [comment]
Sayın arkadaşım sizin için bı link atacağım ilk önce bundan gerekli
bilgileri öğrenmeniz gerekir. Bunun içinde tek kaynak

https://academydexchain.com/.

Buradan gerekli bilgileri edindikten sonra size kendi referans kodumu
göndereceğim bunun üzerinden kayıt olup dexchain coin alıp masternod
yaptıktan sonra nod tutabilirsiniz. Başka türlü dexchain sistemi üzerinden
nod tutmanizin bı yolu yoktur. Numaram 05456001559 bana ulaşabilirsiniz.

30 Oca 2021 Cmt 17:37 tarihinde e2503Necmettin <notifications@github.com>
şunu yazdı:

**Comment by e2503Necmettin** [comment]
biz zaten o aşamaları geçtik
pc de node tutuyoruz. bunu azure da veya amazon da yapmayı istiyoruz.

**Comment by erol7878** [comment]
Bunun şu anda bir yolu yok güncelleme gelir takipte kalın.

30 Oca 2021 Cmt 18:14 tarihinde e2503Necmettin <notifications@github.com>
şunu yazdı:

**Comment by mydexchain-admin** [comment]
Node Azure / AWS nerede olduğunun bir önemi yok. Mydexchain Docker altyapısı kullandığından tüm işletim sistemlerinde çalışabilir.
AWS özelinde 
- EC2 üzerinde çalıştırabilirsiniz.
- EKS üzerinde çalıştırabilirsiniz.
- Fargate ile çalıştırabilirsiniz.
