### ISSUE TITLE
Api desteği hk.

### ISSUE THREAD

**Issue by mduman58** [mydexchain/mydexchain#21]
Merhaba, şu sayfada yer alan (https://mydexchain.io/#/dashboards/documentation) YourApiKey kısmını nereden temin edeceğim ?

Yardımlarınızı rica ederim.

Teşekkürler.

**Comment by myDexChainDXC** [comment]
Merhaba api desteği için ticari faliyet göstermeniz gerekmekte...

**Comment by mduman58** [comment]
Ticari faaliyeti örneklendirebilir misiniz ? Yeni öğreniyorum da :)

**Comment by mydexchain-admin** [comment]
Mobil uygulamadan alabilirsiniz.
Teşekkürler.
