### ISSUE TITLE
Bakiye hakkında

### ISSUE THREAD

**Issue by kubi34** [mydexchain/mydexchain#22]
Merhabalar,
**Yaklaşık 3 gündür aralıksız server çalışıyor ancak mobil cüzdanımı kontrol ettiğimde bakiyemde herhangi bir değişiklik göremedim.**
_“http://{DockerHostIP}:2020/createWallet/{password}”_ **komutu ile oluşturduğum cüzdana mobil ile giriş yapmadım yani
halihazırda kullandığım ve hesabım olan dexchain cüzdanımı mobilde açtım ve oradaki tracker numarasını server da** _"http://{DockerHostIP}:2020/setDextracker/{dexTrackerNumber}”_ **komutu ile setledim. Sorun bundan kaynaklı mı?**

_“http://{DockerHostIP}:2020/createWallet/{password}”_ **ile oluşturduğum cüzdan ne işime yarayacak? Sadece test amaçlı değil mi?**

**Comment by kubi34** [comment]
Proje ile alakalı sorumlu kimse yok mu?

**Comment by newphilipcharles** [comment]
Değerli myDexChain Aktivisti

https://mydexchain.io/#/dashboards/academy

Web sitesindeki Academy’ler ile irtibata geçerek tüm bilgi ve desteği alabilirsiniz. 

İyi çalışmalar.


Dear myDexChain Activist

https://mydexchain.io/#/dashboards/academy

You can get all the information and support by contacting the Academies on the website.

Good work.
