### ISSUE TITLE
Mydexchain Node

### ISSUE THREAD

**Issue by ramazannefes** [mydexchain/mydexchain#23]
Dockerda konteyneri kuruyorum sorunsuz çalışıyor fakat mydexchain.io sitesinde bir türlü online olmuyor bunun için neler yapılabilir ? 
![Mydex](https://user-images.githubusercontent.com/70114450/109420067-99363080-79e1-11eb-889a-8d8476600191.png)

**Comment by mydexchain-admin** [comment]
Konu hakkında network çalışmaları ve algoritma (peer) devam etmekte, sayfayı yenilediğinizde node larınız online olacaktır.

**Comment by kubi34** [comment]
> Konu hakkında network çalışmaları ve algoritma (peer) devam etmekte, sayfayı yenilediğinizde node larınız online olacaktır.

Zaman aşımına uğrayan konteynerlerın sayfadan silinmesi gerekiyor. Önceden deneme amaçlı açıp daha sonra sildiğimiz konteynırlar listede halen mevcut.

**Comment by mydexchain-admin** [comment]
Merhaba, 48 saat offline olan node lar sistemden silinecek, bir sonraki release planına eklendi.
