### ISSUE TITLE
Paket kaçırma hakkında

### ISSUE THREAD

**Issue by kubi34** [mydexchain/mydexchain#24]
![image](https://user-images.githubusercontent.com/54383069/109968513-dcefa980-7d03-11eb-8c46-930613075c22.png)
Merhabalar,
Ubuntu İşletim sistemli bulut sunucuda çalıştırdığım docker engine sorunsuz çalışıyor görünüyor.
Ancak Dexchain sitesinden kontrol ettiğimde bir çok konteynır sürekli online ve offline oluyor ve son aktif zamanları arasında tutarsızlıklar görünüyor.
Bu sorunun çözümü için yardım eder misiniz?

**Comment by kubi34** [comment]
Konu ile alakalı başka bir ekran görüntüsü
![image](https://user-images.githubusercontent.com/54383069/109971738-9ac86700-7d07-11eb-8f4c-c7659e6e1231.png)

**Comment by mydexchain-admin** [comment]
Merhaba Node ların sağlık durumu (health) hakkında bir sonraki release de düzenlenme yapılacaktır.
