### ISSUE TITLE
new wallet adress..

### ISSUE THREAD

**Issue by mhmok41** [mydexchain/mydexchain#6]
[https://dex.mydexpay.io/register.php?userkey=0b725310-41b9-4219-959a-5d8015c14a94](url)

**Comment by mhmok41** [comment]
myDexChain has prepared an infrastructure that will allow you to shop quickly in the blockchain system with its fast infrastructure.
It is a technology that can make transfer transactions in a second and change all balances with its infrastructure compatible with commercial integration. DexChain offers the opportunity to make production by keeping the coin in your account with the dpos algorithm.
Daily DexRate gives crafting rewards based on difficulty level.
The DexChain coin produced is offered for sale on exchanges.
On the Mydexchain platform, companies and individual users can issue their own tokens and use them with the DexChain infrastructure
You can generate DexChain coins by keeping a Full Node from your computer or WPS servers.
You can win dexchain coin award by taking part in Transaction Verification process from Mobile App.
With DexLife's current passive income, you can earn daily staking rewards.
Digital Currency of the New World, DexChain.

**Comment by mhmok41** [comment]
MyDexChain is the best and easiest way to win Dexlife.
The only coin engaged in the production of its own coin.
Project myDexChain offering a new way to produce coin without environmentally sensitive energy consumption. MyDexChain will do a first by bringing a new perspective to Dexlife System with our project. Due to it’s unique algorithm it eliminates wasted energy and server costs. 
Welcome to the world of MyDexChain innovations. We offer you important opportunities.
❓HOW TO EARN WITH MYDEXCHAIN?
 DexChain coin is a value in its own right.  Just like bitcoin, gold, dollar etc.… MyDexChain economy system offers three different earning opportunities in increasing your DexChain number and converting it.
🥇 COIN AWARD PROGRAM
   Like every digital currency, DexChain aims to be used by the masses.  For this, activists have a duty.  According to the initial master's investment made by a new activist who joins the DexChain economic system at the invitation of an activist, a certain proportion of DexChain Coin is given to the inviting activist as a one-time reward by the system.  Reward income rates will decrease as participation increases. (see more (https://academy.mydexchain.io/en/award-program))
🥈 DEXLIFE
   You can deposit your DexChain asset in the Dexlife.  What does it mean?  Dexchain deposited in Dexlife will be linked here for 365 days.  This is an indication of your trust in the MyDexChain economy system.  In return, the system transfers an amount from the generated coins to your wallet every day, at the rate of your investment and Dexrate.  You can either deposit your DexChain balance back to Dexlife or exchange it on exchanges.  If you want to spoil your Dexlife investment on time, a 50% deduction will be made and returned to your wallet.  Dexrate rate is a value that decreases over time.  So the sooner the better approach is used.  Those who trust first are more profitable as in every system.
🥉 RUNNING NODE
   Mydexchain has prepared an infrastructure that will allow you to shop quickly in the blockchain system with its fast infrastructure.
It is a technology that can make transfer transactions in a second and change all balances with its infrastructure compatible with commercial integration. Dexchain offers the opportunity to make production by keeping the coin in your account with the dpos algorithm.
Daily dexrate gives crafting rewards based on difficulty level.
The dexchain coin produced is offered for sale on exchanges.
On the Mydexchain platform, companies and individual users can issue their own tokens and use them with the dexchain infrastructure
You can generate dexchain coins by keeping a Full Node from your computer or WPS servers.
You can win dexchain coin award by taking part in Transaction Verification process from Mobile App.
With DexLife's current passive income, you can earn daily staking rewards.
🏆 Earn Dexchain Coin Daily!!  Digital Currency of the New World, Dexchain!!

**Comment by sametkardas** [comment]
Bilgisayarınızdan veya WPS sunucularından Full Node tutarak dexchain coinleri üretebilirsiniz.
Mobil Uygulamadan İşlem Doğrulama sürecine katılarak dexchain coin ödülü kazanabilirsiniz. 
bu kısmı daha detaylı anlatabilir misiniz?

**Comment by mhmok41** [comment]
En az 10 bin xmd ile 1 masternode kurulumu yapabilirsiniz. 365 gün boyunca
zorluk derecesine göre % 1 e kadar günlük çekilebilir xmd adeti hesabınıza
yatar. 365 gün dolduktan sonra yatırdığınız teminat size geri verilir.
İster tekrar yatırım yapar günlük almaya
Devam edersiniz isterseniz çekip borsada satışa koyabilirisiniz. Öncelikle
buraya kayıt olup node kurulumu için borsalardan koin alıp kazanmaya
başlangıç yapabilirsiniz :
https://mydexpay.io/register.php?userkey=0b725310-41b9-4219-959a-5d8015c14a94
DEX-TRACKER
NEDİR? KİMDİR?
NODE NASIL KURULUR VİDEO <https://youtu.be/QAgf627HyNo>
Full-Node tutucular.. Yani myDexChain kripto ağının tüm verisini
bilgisayarında taşıyan ve servis eden kişi. Klasik blockchain ağlarında
Full-Node tutucular minerlar olarak tanımlanır. myDexChain kripto ağında
Full-Node tutucular Dex-Tracker’lar olarak ifade edilmektedir.
Dex-Tracker’ların işi, oluşan blockların kayıtlarının tutulması olarak
basitçe tanımlanabilir. Dex-Tracker olmak ve bir node kurmak için sistem
gereksinimleri myDexChain Github’ı üzerinde belirtilmektedir. Buna göre bir
bilgisayarın 100GB veri yazmak için disk alanına, 4GB RAM ve ii çekirdekli
bir işlemciye sahip olması gerekmektedir. Belirtilen sistem gereksinimleri
minumum değerler olarak ifade edilir. Ayrıca sahibi olduğunuz Dex-Life
kadar node tutucu olabilirsiniz. Dex-Life’nız yoksa Dex-Tracker
olamazsınız. Örneğin 10 Dex-Life’ınız var ise 10 adet node kurabilirsiniz.
Peki bir kişi neden Dex-Tracker olmak ister. Dex-Tracker olmak bir gelir
kapısıdır. myDexChain kripto ağında hareket eden, alınıp satılan her
değerden bir gönderim ücreti alınmaktadır. Fee olarak da bilinen bu ücret
belirli kurallar çerçevesinde tanımlanmıştır. Örneğin 1000 DexChain
gönderimi yapmak istediğiniz de binde üç oranında bir gönderim ücreti
ödersiniz.
myDexChain kripto ağında gönderimlerden oluşan bu ücretler,
Dex-Tracker’lara ve Cloud Node tutanlara dağıtılır. myDexChain kripto
ağının en güzel özelliklerinden biridir bu. Hiç bir şekilde coinler merkez
bir cüzdana çekilmez sürekli olarak dağıtımı yapılarak paylaştırılır.
Ayrıca sadce DexChain’in gönderimlerinden oluşan gelirler değil myDexChain
üzerinde oluşturulacak tüm coinlerin gönderim ücretleri DexChain olarak
alınır ve paydaşlara dağıtılır.
Bir Dex-Tracker olmak istiyorsanız myDexChain Github’ı üzerinde belirtilen
sistem gereksinimlerini karşılayan bir bilgisayar oluşturup ya da kiralayıp
ağa bağlayarak, Dex-Life’larınızın izin verdiği sayıda Node tutucu
olabilirsiniz......  sonraki adım mobil cüzdan işlemleri
 1-  MOBİL CÜZDAN ANROİD
<https://play.google.com/store/apps/details?id=com.crypto.mydexchain> İOS
Sürümüde vardır  2-  https://academydexchain.com

sametkardas <notifications@github.com>, 18 Oca 2021 Pzt, 21:21 tarihinde
şunu yazdı:
